import React, { useEffect, useState } from 'react';
import { Bot, GripVertical } from 'lucide-react';
import { useNavigation } from '../context/NavigationContext';

export function ConsultAIFloatingButton() {
  const { copilotOpen, setCopilotOpen } = useNavigation();
  const [position, setPosition] = useState(null);
  const [dragState, setDragState] = useState(null);
  useEffect(() => { try { const saved = JSON.parse(localStorage.getItem('himyatra_copilot_position')); if (saved) return setPosition(saved); } catch {} setPosition({ x: Math.max(12, window.innerWidth - 60), y: Math.max(72, window.innerHeight - 70) }); }, []);
  useEffect(() => { if (!dragState) return undefined; const move = (event) => setPosition({ x: Math.min(Math.max(12, event.clientX - dragState.offsetX), Math.max(12, window.innerWidth - 52)), y: Math.min(Math.max(72, event.clientY - dragState.offsetY), Math.max(72, window.innerHeight - 52)) }); const end = () => setDragState(null); window.addEventListener('pointermove', move); window.addEventListener('pointerup', end); return () => { window.removeEventListener('pointermove', move); window.removeEventListener('pointerup', end); }; }, [dragState]);
  useEffect(() => { if (position && !dragState) localStorage.setItem('himyatra_copilot_position', JSON.stringify(position)); }, [position, dragState]);
  return <aside aria-label="Polar AI Copilot Assistant" className="fixed z-40 select-none group" style={position ? { left: position.x, top: position.y } : { right: 12, bottom: 18 }}><span className="absolute -inset-0.5 rounded-full bg-ice-cyan/40 blur-sm animate-pulse pointer-events-none" /><div className="relative w-10 h-10 rounded-full bg-gradient-to-br from-ocean-navy to-research-blue light:from-white light:to-ice-tint border border-ice-cyan/60 shadow-xl"><button type="button" onPointerDown={(event) => { event.preventDefault(); const current = position || { x: window.innerWidth - 60, y: window.innerHeight - 70 }; setDragState({ offsetX: event.clientX - current.x, offsetY: event.clientY - current.y }); }} aria-label="Move AI assistant" title="Drag to move" className="absolute z-10 -top-1 -left-1 p-0.5 rounded-full bg-midnight border border-ice-cyan/50 text-ice-cyan cursor-grab active:cursor-grabbing touch-none"><GripVertical className="w-2.5 h-2.5" /></button><button onClick={() => setCopilotOpen(!copilotOpen)} aria-label="Open AI Copilot" title="Open AI Copilot" className="w-full h-full rounded-full flex items-center justify-center hover:scale-105 active:scale-95 transition-transform"><Bot className="w-5 h-5 text-ice-cyan" /></button></div></aside>;
}
