import React from 'react';
import { Activity, ArrowRight, BarChart3, Navigation, Orbit, Waves } from 'lucide-react';
import { useNavigation } from '../context/NavigationContext';
import { PolarNews } from './PolarNews';

const antarcticaMosaic = 'https://assets.science.nasa.gov/content/dam/science/esd/eo/images/imagerecords/8000/8503/Antarctica_AMO_2008055.jpg/jcr%3Acontent/renditions/cq5dam.web.1280.1280.jpeg';
const auroraSky = 'https://images.unsplash.com/photo-1443926818681-717d074a57af?auto=format&fit=crop&w=2400&q=80';
function PolarGlobe() { return <div className="relative mx-auto w-56 h-56 sm:w-72 sm:h-72 flex items-center justify-center" aria-label="Animated Antarctic polar globe"><div className="absolute inset-0 rounded-full bg-ice-cyan/20 blur-2xl animate-pulse" /><div className="polar-globe relative w-full h-full rounded-full overflow-hidden border border-ice-cyan/60 shadow-[0_0_45px_rgba(56,189,248,0.35)]" style={{ backgroundImage: `url(${antarcticaMosaic})` }}><div className="absolute inset-0 polar-globe-grid" /><div className="absolute inset-[12%] rounded-full border border-ice-cyan/30" /><div className="absolute left-1/2 top-0 bottom-0 w-px bg-ice-cyan/40" /><div className="absolute top-1/2 left-0 right-0 h-px bg-ice-cyan/40" /></div><Orbit className="absolute -right-2 top-8 w-8 h-8 text-ice-cyan/80 animate-pulse" /></div>; }
const quickLaunches = [
  { id: 'map', label: 'Trajectory Map', icon: Navigation },
  { id: 'sea-level-impact', label: 'Melt and Sea Level Impact', icon: Waves },
  { id: 'dashboard', label: 'Polar Navigation Analysis', icon: Activity },
  { id: 'visualizations', label: 'Scientific Diagnostics', icon: BarChart3 },
];

export function LandingPage() { const { setCurrentTab } = useNavigation(); return <div className="relative isolate w-full overflow-hidden py-8 sm:py-10 select-none"><div className="absolute inset-0 -z-20 bg-cover bg-center bg-fixed opacity-[0.14] light:opacity-[0.08] saturate-75" style={{ backgroundImage: `url(${auroraSky})` }} /><div className="absolute inset-0 -z-10 bg-gradient-to-b from-midnight/72 via-midnight/80 to-midnight/86 light:from-white/78 light:via-white/84 light:to-slate-50/90" /><div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 w-full space-y-8"><section className="relative overflow-hidden rounded-3xl border border-slate-700/70 light:border-slate-200 min-h-[330px] px-6 py-9 sm:px-10 sm:py-12"><div className="absolute inset-0 bg-cover bg-center opacity-[0.16] light:opacity-[0.14] saturate-75 light:saturate-50" style={{ backgroundImage: `url(${antarcticaMosaic})` }} /><div className="absolute inset-0 bg-gradient-to-r from-midnight via-midnight/85 to-ocean-navy/55 light:from-white/95 light:via-white/84 light:to-ice-tint/58" /><div className="relative z-10 grid grid-cols-1 lg:grid-cols-[1.2fr_0.8fr] items-center gap-8"><div className="text-left max-w-3xl"><h1 className="text-3xl sm:text-[2.6rem] lg:text-5xl xl:text-6xl text-white light:text-ocean-navy uppercase leading-[1.08] tracking-[0.02em]" style={{ fontFamily: '"Times New Roman", Times, Georgia, serif', fontWeight: 600 }}>Antarctic Sea Ice &amp;<br />Navigation</h1><p className="mt-3 text-sm sm:text-base font-mono font-semibold tracking-wide text-ice-cyan light:text-research-blue">HimYatra : The polar journey</p><div className="flex flex-wrap items-center gap-3 pt-7">{quickLaunches.map(({ id, label, icon: Icon }) => <button key={id} onClick={() => setCurrentTab(id)} className="group inline-flex items-center gap-2 rounded-xl border border-sky-200/35 bg-gradient-to-r from-sky-400 via-ice-cyan to-cyan-300 px-5 py-3 text-sm font-bold text-midnight shadow-[0_8px_22px_rgba(56,189,248,0.22)] transition duration-200 hover:-translate-y-0.5 hover:shadow-[0_14px_28px_rgba(56,189,248,0.38)] focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-ice-cyan"><Icon className="w-4 h-4" />{label}<ArrowRight className="w-4 h-4 transition-transform group-hover:translate-x-0.5" /></button>)}</div></div><PolarGlobe /></div></section><section aria-label="Polar news feed" className="relative"><PolarNews embedded /></section></div></div>; }
