import React, { useEffect, useMemo, useRef, useState } from 'react';
import { AlertTriangle, Loader2, Play, Snowflake } from 'lucide-react';
import { getActiveIcebergs, runIcebergMeltSimulation } from '../services/api';
import { useNavigation } from '../context/NavigationContext';

const YEARS = [1, 5, 10, 20, 30], SCENARIOS = ['low', 'moderate', 'high'];
const photo = 'https://images.unsplash.com/photo-1635810766763-979377656b4b?auto=format&fit=crop&w=1400&q=85';
const fmt = (v, d = 1) => v == null || Number.isNaN(Number(v)) ? '--' : Number(v).toLocaleString(undefined, { maximumFractionDigits: d });
const Field = ({ label, children }) => <label className="block text-xs font-medium text-slate-300">{label}{children}</label>;
const fieldClass = 'iceberg-control mt-1.5 w-full appearance-none rounded-xl border border-sky-200/25 px-3 py-3 text-sm shadow-inner shadow-black/30 outline-none transition duration-200 placeholder:text-slate-500 hover:border-sky-300/50 focus:border-ice-cyan focus:ring-2 focus:ring-ice-cyan/25';
function Card({ children, className = '' }) { return <section className={`rounded-2xl border border-sky-200/25 shadow-[0_24px_60px_rgba(0,0,0,0.5),0_0_32px_rgba(56,189,248,0.08)] backdrop-blur-md ${className}`} style={{ backgroundImage: "linear-gradient(135deg, rgba(15, 23, 42, 0.91), rgba(7, 18, 32, 0.87)), url('https://static.scientificamerican.com/sciam/cache/file/1BACC933-1D88-4EB8-9B73C5B296F102F5_source.jpg?crop=4%3A3%2Csmart&w=1200')", backgroundSize: 'cover', backgroundPosition: 'center' }}>{children}</section>; }
function Metric({ label, value, unit = '' }) { return <div className="rounded-xl border border-sky-300/20 bg-midnight/75 p-4 backdrop-blur-sm transition hover:-translate-y-0.5 hover:border-ice-cyan/70 hover:bg-midnight/90"><div className="text-[10px] font-mono uppercase tracking-wider text-sky-200/75">{label}</div><div className="mt-1 font-mono text-lg font-bold text-white">{value}<span className="ml-1 text-[10px] font-normal text-slate-300">{unit}</span></div></div>; }

export function SeaLevelImpact() {
  const { icebergs } = useNavigation();
  const [items, setItems] = useState(icebergs || []), [id, setId] = useState(''), [years, setYears] = useState(30), [scenario, setScenario] = useState('moderate');
  const [form, setForm] = useState({ length_m: '', width_m: '', thickness_m: '', shape_factor: '0.78' });
  const [result, setResult] = useState(null), [loading, setLoading] = useState(false), [loadingData, setLoadingData] = useState(true), [error, setError] = useState('');
  const detailsRef = useRef(null);
  useEffect(() => { let alive = true; getActiveIcebergs().then((data) => { if (alive && Array.isArray(data)) setItems(data); }).finally(() => alive && setLoadingData(false)); return () => { alive = false; }; }, []);
  const iceberg = useMemo(() => items.find((x) => (x.id || x.iceberg_id) === id), [items, id]);
  useEffect(() => { if (!iceberg) return; setForm({ length_m: iceberg.length_m ?? '', width_m: iceberg.width_m ?? '', thickness_m: iceberg.thickness_m ?? '', shape_factor: '0.78' }); setResult(null); setError(''); requestAnimationFrame(() => detailsRef.current?.scrollIntoView({ behavior: 'smooth', block: 'start' })); }, [iceberg]);
  const change = (key, value) => setForm((old) => ({ ...old, [key]: value }));
  const run = async () => { if (!iceberg) return setError('Select an iceberg first.'); if (![form.length_m, form.width_m, form.thickness_m].every((x) => Number(x) > 0)) return setError('Enter valid length, width, and thickness.'); setLoading(true); setResult(null); setError(''); try { setResult(await runIcebergMeltSimulation({ iceberg_id: iceberg.id || iceberg.iceberg_id, latitude: Number(iceberg.latitude), longitude: Number(iceberg.longitude), length_m: Number(form.length_m), width_m: Number(form.width_m), thickness_m: Number(form.thickness_m), shape_factor: Number(form.shape_factor), dimensions_status: 'estimated', horizon_years: years, scenario, use_scenario_baseline: true })); } catch (e) { setError(e.response?.data?.detail || 'The simulation could not be completed.'); } finally { setLoading(false); } };
  const last = result?.checkpoints?.at(-1)?.volume_m3, initial = result?.initial_state.volume_m3;
  const details = iceberg && [['Latitude', fmt(iceberg.latitude, 2), '°'], ['Longitude', fmt(iceberg.longitude, 2), '°'], ['Observed area', fmt(iceberg.area_sq_km), 'km²'], ['Length', fmt(iceberg.length_m), 'm'], ['Width', fmt(iceberg.width_m), 'm'], ['Thickness', fmt(iceberg.thickness_m), 'm'], ['Source', iceberg.source || '--', '']];
  return <div className="w-full max-w-7xl mx-auto rounded-3xl bg-cover bg-center bg-fixed px-4 py-8 sm:px-6 sm:py-10" style={{ backgroundImage: "linear-gradient(rgba(2,6,23,.76),rgba(2,6,23,.84)),url('https://assets.science.nasa.gov/content/dam/science/esd/eo/images/imagerecords/8000/8503/Antarctica_AMO_2008055.jpg/jcr%3Acontent/renditions/cq5dam.web.1280.1280.jpeg')" }}><div className="mb-6"><div className="text-[11px] font-mono font-bold tracking-widest uppercase text-ice-cyan">Iceberg simulator</div><h1 className="text-2xl sm:text-4xl font-black uppercase text-white">Melt & sea-level impact</h1></div>
    <Card className="p-5 sm:p-7"><div className="flex items-center gap-3 border-b border-slate-700/70 pb-5"><div className="rounded-xl bg-ice-cyan/15 p-2 text-ice-cyan"><Snowflake className="w-5 h-5" /></div><h2 className="font-bold text-white">Simulation inputs</h2></div><div className="mt-6 grid grid-cols-1 lg:grid-cols-2 gap-6 lg:gap-10"><div className="space-y-4"><div className="text-[10px] font-mono uppercase tracking-widest text-ice-cyan">Iceberg setup</div><Field label="Iceberg ID"><select value={id} onChange={(e) => setId(e.target.value)} className={fieldClass}><option value="">{loadingData ? 'Loading iceberg data…' : 'Select iceberg'}</option>{items.map((x) => <option key={x.id || x.iceberg_id} value={x.id || x.iceberg_id}>{x.id || x.iceberg_id}</option>)}</select></Field><div className="grid grid-cols-2 gap-4"><Field label="Projection"><select value={years} onChange={(e) => setYears(Number(e.target.value))} className={fieldClass}>{YEARS.map((x) => <option key={x} value={x}>{x} years</option>)}</select></Field><Field label="Scenario"><select value={scenario} onChange={(e) => setScenario(e.target.value)} className={fieldClass}>{SCENARIOS.map((x) => <option key={x} value={x}>{x}</option>)}</select></Field></div></div><div className="space-y-4 lg:border-l lg:border-sky-200/15 lg:pl-10"><div className="text-[10px] font-mono uppercase tracking-widest text-ice-cyan">Melting parameters</div><div className="grid grid-cols-1 sm:grid-cols-3 gap-4">{[['length_m', 'Length (m)'], ['width_m', 'Width (m)'], ['thickness_m', 'Thickness (m)']].map(([key, label]) => <Field key={key} label={label}><input type="number" min="0" value={form[key]} onChange={(e) => change(key, e.target.value)} className={fieldClass} /></Field>)}</div><Field label="Shape factor"><input type="number" min=".01" max="1" step=".01" value={form.shape_factor} onChange={(e) => change('shape_factor', e.target.value)} className={fieldClass} /></Field><button onClick={run} disabled={loading || !iceberg} className="inline-flex w-full items-center justify-center gap-2 rounded-xl border border-sky-200/30 bg-gradient-to-r from-sky-400 via-ice-cyan to-cyan-300 px-6 py-4 text-base font-black text-midnight shadow-[0_12px_28px_rgba(56,189,248,0.28)] transition duration-200 hover:-translate-y-0.5 hover:shadow-[0_16px_34px_rgba(56,189,248,0.42)] disabled:opacity-40">{loading ? <Loader2 className="w-5 h-5 animate-spin" /> : <Play className="w-5 h-5" />}{loading ? 'Simulating…' : 'Get your result'}</button></div></div>{error && <div className="mt-5 flex gap-2 rounded-xl border border-amber-400/40 bg-amber-400/10 p-3 text-sm text-amber-200"><AlertTriangle className="w-4 h-4 shrink-0" />{error}</div>}</Card>
    <div ref={detailsRef} className="mt-6"><Card className="overflow-hidden min-h-[480px]">{!result ? <div className="relative min-h-[480px] overflow-hidden"><img src={photo} alt="Antarctic iceberg" className="absolute inset-0 h-full w-full object-cover opacity-[.14] saturate-50" /><div className="absolute inset-0 bg-midnight/80" /><div className="relative p-6 sm:p-8">{iceberg ? <><div className="text-[10px] font-mono uppercase tracking-widest text-ice-cyan">Selected iceberg</div><h2 className="mt-2 text-3xl font-black text-white">{id}</h2><div className="mt-6 grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4 [&>*:last-child]:sm:col-span-2 [&>*:last-child]:lg:col-span-4">{details.map(([label, value, unit]) => <Metric key={label} label={label} value={value} unit={unit} />)}</div></> : <div className="min-h-[190px]" />}</div></div> : <div className="p-6 sm:p-8"><div className="border-b border-slate-700/70 pb-5"><div className="text-[10px] font-mono uppercase tracking-widest text-ice-cyan">Simulation result</div><h2 className="mt-1 font-bold text-white">{id} · {years} years</h2></div><div className="mt-5 grid grid-cols-2 lg:grid-cols-4 gap-4"><Metric label="Initial volume" value={fmt(initial)} unit="m³" /><Metric label="Volume lost" value={fmt(result.totals?.melted_ice_volume_m3)} unit="m³" /><Metric label="Ice melted" value={fmt(initial ? (1 - last / initial) * 100 : null)} unit="%" /><Metric label="Sea-level" value={result.totals ? `${fmt(result.totals.net_sea_level_equivalent_m * 1000, 6)} mm` : '--'} /></div><div className="mt-5 grid grid-cols-1 sm:grid-cols-2 gap-4"><Metric label="Meltwater produced" value={fmt(result.totals?.meltwater_m3)} unit="m³" /><Metric label="Final ice volume" value={fmt(last)} unit="m³" /></div></div>}</Card></div>
  </div>;
}
